server:
  port: 9010
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
  # 跨域访问
  instance:
    prefer-ip-address: true
# jwt
jwt:
  config:
    key: wocaonigedjnitamakendingbuzhidaoyanshishenmehahaha
    ttl: 3600000
# zuul网关配置
zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000
  prefix: /manager
  routes:
    # 配置base路由
    tensquare-base:
      path: /base/**  # 拦截所有为base开头的路径
      serviceId: tensquare-base # 跳转到base服务
    tensquare-article:
      path: /article/**
      serviceId: tensquare-article
    tensquare-friend:
      path: /friend/**
      serviceId: tensquare-friend
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-recruit:
      path: /recruit/**
      serviceId: tensquare-recruit
    tensquare-search:
      path: /search/**
      serviceId: tensquare-search
    tensquare-sms:
      path: /sms/**
      serviceId: tensquare-sms
    tensquare-spit:
      path: /spit/**
      serviceId: tensquare-spit
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
