server:
  port: 9001
spring:
  application:
    name: tensquare_base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.114.73:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 199461
  jpa:
    show-sql: true
    database: mysql