server:
  port: 9000
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.114.73:3306/tensquare_?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql