server:
  port: 9009
spring:
  application:
    name: tensquare-friend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.114.73:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
  # 跨域访问
  instance:
    prefer-ip-address: true
# jwt
jwt:
  config:
    key: wocaonigedjnitamakendingbuzhidaoyanshishenmehahaha
    ttl: 3600000