server:
  port: 9003
spring:
  application:
    name: tensquare-article
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.114.73:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
  redis:
    host: 118.24.114.73
    password: 123456
    port: 6379